### ISSUE TITLE
Fatal error on checkout page with PHP < 8.0.0

### ISSUE THREAD

**Issue by rvdsteege** [dpdconnect/woocommerce-shipping#79]
This plugin produces a fatal error on the WooCommerce checkout page for PHP versions `< 8.0.0` since [https://github.com/dpdconnect/woocommerce-shipping/commit/aa790cfc46bcf6d0faf5b81d170a9dcbb2cd75aa#diff-4a0e7f006983320a633d0972fcacd3286431c34fad4765b64e218829c9ca4f88](https://github.com/dpdconnect/woocommerce-shipping/commit/aa790cfc46bcf6d0faf5b81d170a9dcbb2cd75aa#diff-4a0e7f006983320a633d0972fcacd3286431c34fad4765b64e218829c9ca4f88) (plugin version `1.4.5`).

```
Fatal error: Uncaught TypeError: Typed property DpdConnect\classes\shippingmethods\DPDShippingMethod::$cost must be an instance of DpdConnect\classes\shippingmethods\mixed, string used in /public_html/wp-content/plugins/dpdconnect/classes/shippingmethods/DPDShippingMethod.php:100

Stack trace:
#0 /public_html/wp-content/plugins/dpdconnect/classes/shippingmethods/DPDShippingMethod.php(72): DpdConnect\classes\shippingmethods\DPDShippingMethod->init()
#1 /public_html/wp-content/plugins/dpdconnect/classes/Handlers/Pickup.php(45): DpdConnect\classes\shippingmethods\DPDShippingMethod->__construct()
#2 /public_html/wp-includes/class-wp-hook.php(324): DpdConnect\classes\Handlers\Pickup::addColumn()
#3 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /public_html/wp-includes/plugin.php(517): in /public_html/wp-content/plugins/dpdconnect/classes/shippingmethods/DPDShippingMethod.php on line 100
```

**Comment by rvdsteege** [comment]
Also in https://github.com/dpdconnect/woocommerce-shipping/blob/37cbb2cf3a5a8d8aab39c87182474001586e8fc1/classes/OrderTransformer.php#L11

**Comment by rvdsteege** [comment]
Thanks, that's what I thought. Maybe the `Requires PHP` can be added in the plugin headers to reflect this requirement?

- https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

https://github.com/dpdconnect/woocommerce-shipping/blob/37cbb2cf3a5a8d8aab39c87182474001586e8fc1/dpdconnect.php#L5-L15
